### ISSUE TITLE
SyntaxError: This experimental syntax requires enabling the parser plugin: 'optionalChaining'

### ISSUE THREAD

**Issue by jasonkneen** [tidev/hyperloop.next#369]
When enabling hyperloop in a project, and using optional changing so

`e.result?.percent_off`

you can't build on Android -- you get the error in the title as hyperloop scans files and those files use optional changing

The solution is to either not use HL or remove all optional chaining.

**Comment by m1ga** [comment]
We can test it with https://github.com/tidev/hyperloop.next/pull/370 once the [Actions are updated](https://github.com/tidev/hyperloop.next/pull/371) .

**Comment by hansemannn** [comment]
This should now be possible
