### ISSUE TITLE
Xcode 15: cannot figure out objc return result

### ISSUE THREAD

**Issue by m1ga** [tidev/hyperloop.next#380]
Issue for some Slack users:

Hyperloop, Xcode 15 (Beta 8 was working)

```
Error: cannot figure out objc return result
    at Object.getObjCReturnResult (/Users/user/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/util.js:626:8)
    at /Users/user/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/block.js:113:31
    at Array.forEach (<anonymous>)
    at Object.generateBlockWrapper (/Users/BatMan/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/block.js:109:19)
    at /Users/user/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/index.js:290:39
    at Array.forEach (<anonymous>)
    at /Users/user/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/index.js:289:18
    at Array.forEach (<anonymous>)
    at /Users/user/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/index.js:282:43
    at /Users/user/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/node_modules/async/dist/async.js:473:16
```

Place is:
https://github.com/tidev/hyperloop.next/blob/6e9eae76664c4b4f5ab45f6428e4fd5c620cbbab/iphone/hooks/generate/util.js#L626

return value:
```
{
  encoding: '{?=qiIq}',
  name: 'actualTime',
  type: 'record',
  value: 'CMTime'
}
```

**Comment by hansemannn** [comment]
Is there a sample code for this?

**Comment by m1ga** [comment]
I only created it so it won't get lost. Here are the slack threads where people have the issue:

https://tidev.slack.com/archives/C03CVQX2A/p1695674912584769
https://tidev.slack.com/archives/C0B2EUWRK/p1695733764354989?thread_ts=1694798671.092719&cid=C0B2EUWRK
https://tidev.slack.com/archives/C03CVQX2A/p1695094751177669

but it sounds like its during the build process, so no app code yet.

**Comment by hansemannn** [comment]
Honestly, I have no idea how to fix this. It seems like struct encodings are not properly handled, but I don't know what needs to be changed to do so.

**Comment by Arood** [comment]
I'm also experiencing this

```
{
  encoding: '{?=qiIq}',
  name: 'actualTime',
  type: 'record',
  value: 'CMTime'
}
[LiveView] Error: cannot figure out objc return result
    at Object.getObjCReturnResult (/Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/util.js:626:8)
    at /Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/block.js:113:31
    at Array.forEach (<anonymous>)
    at Object.generateBlockWrapper (/Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/block.js:109:19)
    at /Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/index.js:290:39
    at Array.forEach (<anonymous>)
    at /Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/index.js:289:18
    at Array.forEach (<anonymous>)
    at /Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/generate/index.js:282:43
    at /Users/arood/Library/Application Support/Titanium/modules/iphone/hyperloop/7.0.5/hooks/node_modules/async/dist/async.js:473:16
```

There's also a lot of "Not sure how to handle"-lines before this, that I'm not sure if it's related, but it starts with some lines mentioning CMTime so maybe?

```
Not sure how to handle: name= transform type= record value= simd_float4x4
Not sure how to handle: name= transform type= record value= simd_float4x4
Not sure how to handle: name= BOOL type= unknown type: 119 value= BOOL
Not sure how to handle: name= duration type= record value= CMTime
Not sure how to handle: name= BOOL type= unknown type: 119 value= BOOL
Not sure how to handle: name= duration type= record value= CMTime
Not sure how to handle: name= timestamp type= record value= CMTime
Not sure how to handle: name= timestamp type= record value= CMTime
Not sure how to handle: name= BOOL type= unknown type: 119 value= BOOL
Not sure how to handle: name= duration type= record value= CMTime
Not sure how to handle: name= duration type= record value= CMTime
Not sure how to handle: name= duration type= record value= CMTime
Not sure how to handle: name= duration type= record value= CMTime
Not sure how to handle: name= BOOL type= unknown type: 119 value= BOOL
Not sure how to handle: name= CFTimeInterval type= unknown type: 119 value= CFTimeInterval
...and lots more
```

If there's anything else I can provide let me know, I'm very inclined to get this fixed so I can get my app starting :)

**Comment by Arood** [comment]
It seems like importing UIActivityViewController triggers the problem, if you need a way to recreate it.

`var UIActivityViewController = require('UIKit/UIActivityViewController');`

**Comment by johnstan** [comment]
Same with 12.2.1.GA on an Intel Mac

**Comment by williamycx** [comment]
Having the same issue with SDK 12.2.1.GA and Hyperloop 7.0.5 on a Intel Mac.

**Comment by Marvbuster** [comment]
Same issue here on 12.2.1.GA, macos 14.1 and xcode 15.0.1

**Comment by hansemannn** [comment]
Hi everyone! This issue has finally been addressed - you can find the new release here: 

https://github.com/tidev/hyperloop.next/releases/tag/v7.0.6

Please note that there is one open, unrelated issue regarding Cocoapods. It may be only on my system, but just in case you are running into it, please report it in a separate issue, so it can be tracked. Thank you!

**Comment by hansemannn** [comment]
Update: The hyperloop-examples sample app is working fine - the issue was just an outdated Localytics SDK dependency. All up to date now :)

**Comment by francisco-alvarado-espol** [comment]
Hi! Is it working on Xcode 15.0.1?

**Comment by mbespol** [comment]
Funcionando en Mac M1 (OS Sonoma 14.2.1) y XCode 15.2, Adicionalmente cuando se intenta lanzar el simulador da el siguiente error: “metabase” no se puede abrir porque no se puede verificar el desarrollador. El cual se soluciona, desde las opciones de "Privacidad y Seguridad", volver a ejecutar y luego al mensaje "Abrir"

**Comment by mbespol** [comment]
It works on Mac M1 (OS Sonoma 14.2.1) and XCode 15.2, in addition, when trying to start the simulator the following error appears: The “metabase” cannot be opened because the developer cannot be verified. Which is solved, from the “Privacy and Security” options, run again and then the “Open” message appears.
